# DeathMessages by Joshb_ (Original DeathMessagesPrime by CosmoConsole)
# All configs from this plugin has an auto updater. Meaning if I add a value in the config from updates,
# the value will be automatically added without regenerating the configs.
#
# Disable the default messages from minecraft
Disable-Default-Messages: true

# Add a prefix to all death messages? (Prefix from Messages.yml)
Add-Prefix-To-All-Messages: true

# If enabled, weapon kills will default to a defined kill if the weapon does not have a custom display name
Disable-Weapon-Kill-With-No-Custom-Name:
  Enabled: false
  Source:
    Projectile:
      Default-To: Projectile-Unknown
    Weapon:
      Default-To: Melee

# If enabled, if a player was pushed into the void by a killer, and void kill message is not defined, use melee death.
# This option is ignored if Default-Natural-Death-Not-Defined is set to true.
Default-Melee-Last-Damage-Not-Defined: true

# If enabled, for example, if a player was pushed into the void by a killer,
# and void kill message is not defined in the player section, natural death message will be used.
Default-Natural-Death-Not-Defined: true

# Set the listener call priority for death messages.
# LOWEST, LOW, NORMAL, HIGH, HIGHEST are allowed
# MONITOR is not support and is defaulted to HIGH
Death-Listener-Priority: HIGH

Expire-Last-Damage:
  # How long until the last mob that damaged a player expires? (Becomes a natural death cause)
  # Default: 7
  Expire-Mob: 7

# If enabled, death messages will only be sent to players in the same world the player died in.
Per-World-Messages: false

# Group worlds together to send messages to a group of worlds instead of messages per world.
# Per-World-Messages must be set to true, otherwise, this setting is ignored.
# World groups are unlimited, and the key names can be named whatever you want, they are ignored
# and not used in the code.
# If a world a player dies in is not specified, it will only broadcast to the world the player died in.
World-Groups:
  1:
    - world
    - world_nether
    - world_the_end
