name: DeathMessages
version: ${version}
main: dev.mrshawn.deathmessages.DeathMessages
api-version: 1.13
folia-supported: true
softdepend:
  - MythicMobs
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
  - DiscordBotAPI
  - DiscordSRV
  - CombatLogX
authors:
  - CosmoConsole
  - Joshb_
  - MrShawn
  - Dreeam-qwq
commands:
  deathmessages:
    description: Main plugin command
    aliases: [dm]
  deathmessagestoggle:
    description: Alias for /dm toggle in one command
    aliases: [dmt, dmtoggle]