name: DeathMessages
version: 1.1.8
main: net.joshb.deathmessages.DeathMessages
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
  - DiscordBotAPI
  - DiscordSRV
author: Joshb_
commands:
  deathmessages:
    description: Main plugin command
    aliases: [dm]