name: DeathMessages
version: 1.0.0
main: net.joshb.deathmessages.DeathMessages
api-version: 1.13
softdepend:
  - PlaceholderAPI
  - WorldEdit
  - WorldGuard
category: test
author: Joshb_
commands:
  deathmessages:
    description: Main plugin command
    aliases: [dm]