name: Build DeathMessages
on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build

      - name: Release DeathMessages
        if: "contains(github.event.commits[0].message, '[Release]')"
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "DeathMessages v1.4.18"
          automatic_release_tag: "1.4.18"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "Core/build/libs/DeathMessages-*.jar"
          prerelease: false

      - name: Upload DeathMessages DevBuild
        if: github.ref_name == 'master'
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "DeathMessages v1.4.18"
          automatic_release_tag: "dev-build"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "Core/build/libs/DeathMessages-*.jar"
          prerelease: true

      - name: Upload DeathMessages Nightly
        if: github.ref_name == 'dev'
        uses: actions/upload-artifact@main
        with:
          name: DeathMessages-Nightly
          path: Core/build/libs/DeathMessages-*.jar
